/**
 * generated by Xtext
 */
package autoevaluacion.ui.contentassist;

import autoevaluacion.ui.contentassist.AbstractAutoevaluacionProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class AutoevaluacionProposalProvider extends AbstractAutoevaluacionProposalProvider {
}
