/*
* generated by Xtext
*/
package autoevaluacion.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import autoevaluacion.services.AutoevaluacionGrammarAccess;

public class AutoevaluacionParser extends AbstractContentAssistParser {
	
	@Inject
	private AutoevaluacionGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected autoevaluacion.ui.contentassist.antlr.internal.InternalAutoevaluacionParser createParser() {
		autoevaluacion.ui.contentassist.antlr.internal.InternalAutoevaluacionParser result = new autoevaluacion.ui.contentassist.antlr.internal.InternalAutoevaluacionParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getHojaAccess().getAlternatives(), "rule__Hoja__Alternatives");
					put(grammarAccess.getRespuestaAccess().getAlternatives(), "rule__Respuesta__Alternatives");
					put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEjercicioAccess().getGroup(), "rule__Ejercicio__Group__0");
					put(grammarAccess.getEjercicioAccess().getGroup_5(), "rule__Ejercicio__Group_5__0");
					put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
					put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
					put(grammarAccess.getClasicoAccess().getGroup(), "rule__Clasico__Group__0");
					put(grammarAccess.getClasicoAccess().getGroup_9(), "rule__Clasico__Group_9__0");
					put(grammarAccess.getWizardAccess().getGroup(), "rule__Wizard__Group__0");
					put(grammarAccess.getWizardAccess().getGroup_9(), "rule__Wizard__Group_9__0");
					put(grammarAccess.getWizardAdaptativoAccess().getGroup(), "rule__WizardAdaptativo__Group__0");
					put(grammarAccess.getWizardAdaptativoAccess().getGroup_9(), "rule__WizardAdaptativo__Group_9__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getRespuestaUnicaAccess().getGroup(), "rule__RespuestaUnica__Group__0");
					put(grammarAccess.getRespuestaUnicaAccess().getGroup_3(), "rule__RespuestaUnica__Group_3__0");
					put(grammarAccess.getRespuestaUnicaAccess().getGroup_3_3(), "rule__RespuestaUnica__Group_3_3__0");
					put(grammarAccess.getRespuestaUnicaAccess().getGroup_4(), "rule__RespuestaUnica__Group_4__0");
					put(grammarAccess.getRespuestaUnicaAccess().getGroup_4_3(), "rule__RespuestaUnica__Group_4_3__0");
					put(grammarAccess.getRespuestaMultipleAccess().getGroup(), "rule__RespuestaMultiple__Group__0");
					put(grammarAccess.getRespuestaMultipleAccess().getGroup_3(), "rule__RespuestaMultiple__Group_3__0");
					put(grammarAccess.getRespuestaMultipleAccess().getGroup_3_3(), "rule__RespuestaMultiple__Group_3_3__0");
					put(grammarAccess.getRespuestaMultipleAccess().getGroup_4(), "rule__RespuestaMultiple__Group_4__0");
					put(grammarAccess.getRespuestaMultipleAccess().getGroup_4_3(), "rule__RespuestaMultiple__Group_4_3__0");
					put(grammarAccess.getTextoLibreAccess().getGroup(), "rule__TextoLibre__Group__0");
					put(grammarAccess.getTextoLibreAccess().getGroup_3(), "rule__TextoLibre__Group_3__0");
					put(grammarAccess.getTextoLibreAccess().getGroup_3_3(), "rule__TextoLibre__Group_3_3__0");
					put(grammarAccess.getTextoLibreAccess().getGroup_4(), "rule__TextoLibre__Group_4__0");
					put(grammarAccess.getTextoLibreAccess().getGroup_4_3(), "rule__TextoLibre__Group_4_3__0");
					put(grammarAccess.getOrdenacionAccess().getGroup(), "rule__Ordenacion__Group__0");
					put(grammarAccess.getOrdenacionAccess().getGroup_3(), "rule__Ordenacion__Group_3__0");
					put(grammarAccess.getOrdenacionAccess().getGroup_3_3(), "rule__Ordenacion__Group_3_3__0");
					put(grammarAccess.getOrdenacionAccess().getGroup_4(), "rule__Ordenacion__Group_4__0");
					put(grammarAccess.getOrdenacionAccess().getGroup_4_3(), "rule__Ordenacion__Group_4_3__0");
					put(grammarAccess.getEjercicioAccess().getNameAssignment_1(), "rule__Ejercicio__NameAssignment_1");
					put(grammarAccess.getEjercicioAccess().getEnunciadoAssignment_4(), "rule__Ejercicio__EnunciadoAssignment_4");
					put(grammarAccess.getEjercicioAccess().getPuntuacionEjAssignment_5_1(), "rule__Ejercicio__PuntuacionEjAssignment_5_1");
					put(grammarAccess.getEjercicioAccess().getCategoriaAssignment_7(), "rule__Ejercicio__CategoriaAssignment_7");
					put(grammarAccess.getEjercicioAccess().getOrderAssignment_9(), "rule__Ejercicio__OrderAssignment_9");
					put(grammarAccess.getEjercicioAccess().getRespuestaAssignment_11(), "rule__Ejercicio__RespuestaAssignment_11");
					put(grammarAccess.getClasicoAccess().getPuntuacionAssignment_3(), "rule__Clasico__PuntuacionAssignment_3");
					put(grammarAccess.getClasicoAccess().getPenalizacionAssignment_5(), "rule__Clasico__PenalizacionAssignment_5");
					put(grammarAccess.getClasicoAccess().getEjerciciosAssignment_8(), "rule__Clasico__EjerciciosAssignment_8");
					put(grammarAccess.getClasicoAccess().getEjerciciosAssignment_9_1(), "rule__Clasico__EjerciciosAssignment_9_1");
					put(grammarAccess.getWizardAccess().getPuntuacionAssignment_3(), "rule__Wizard__PuntuacionAssignment_3");
					put(grammarAccess.getWizardAccess().getPenalizacionAssignment_5(), "rule__Wizard__PenalizacionAssignment_5");
					put(grammarAccess.getWizardAccess().getEjerciciosAssignment_8(), "rule__Wizard__EjerciciosAssignment_8");
					put(grammarAccess.getWizardAccess().getEjerciciosAssignment_9_1(), "rule__Wizard__EjerciciosAssignment_9_1");
					put(grammarAccess.getWizardAdaptativoAccess().getPuntuacionAssignment_3(), "rule__WizardAdaptativo__PuntuacionAssignment_3");
					put(grammarAccess.getWizardAdaptativoAccess().getPenalizacionAssignment_5(), "rule__WizardAdaptativo__PenalizacionAssignment_5");
					put(grammarAccess.getWizardAdaptativoAccess().getEjerciciosAssignment_8(), "rule__WizardAdaptativo__EjerciciosAssignment_8");
					put(grammarAccess.getWizardAdaptativoAccess().getEjerciciosAssignment_9_1(), "rule__WizardAdaptativo__EjerciciosAssignment_9_1");
					put(grammarAccess.getRespuestaUnicaAccess().getCorrectasAssignment_3_2(), "rule__RespuestaUnica__CorrectasAssignment_3_2");
					put(grammarAccess.getRespuestaUnicaAccess().getCorrectasAssignment_3_3_1(), "rule__RespuestaUnica__CorrectasAssignment_3_3_1");
					put(grammarAccess.getRespuestaUnicaAccess().getAlternativasAssignment_4_2(), "rule__RespuestaUnica__AlternativasAssignment_4_2");
					put(grammarAccess.getRespuestaUnicaAccess().getAlternativasAssignment_4_3_1(), "rule__RespuestaUnica__AlternativasAssignment_4_3_1");
					put(grammarAccess.getRespuestaMultipleAccess().getCorrectasAssignment_3_2(), "rule__RespuestaMultiple__CorrectasAssignment_3_2");
					put(grammarAccess.getRespuestaMultipleAccess().getCorrectasAssignment_3_3_1(), "rule__RespuestaMultiple__CorrectasAssignment_3_3_1");
					put(grammarAccess.getRespuestaMultipleAccess().getAlternativasAssignment_4_2(), "rule__RespuestaMultiple__AlternativasAssignment_4_2");
					put(grammarAccess.getRespuestaMultipleAccess().getAlternativasAssignment_4_3_1(), "rule__RespuestaMultiple__AlternativasAssignment_4_3_1");
					put(grammarAccess.getTextoLibreAccess().getCorrectasAssignment_3_2(), "rule__TextoLibre__CorrectasAssignment_3_2");
					put(grammarAccess.getTextoLibreAccess().getCorrectasAssignment_3_3_1(), "rule__TextoLibre__CorrectasAssignment_3_3_1");
					put(grammarAccess.getTextoLibreAccess().getAlternativasAssignment_4_2(), "rule__TextoLibre__AlternativasAssignment_4_2");
					put(grammarAccess.getTextoLibreAccess().getAlternativasAssignment_4_3_1(), "rule__TextoLibre__AlternativasAssignment_4_3_1");
					put(grammarAccess.getOrdenacionAccess().getCorrectasAssignment_3_2(), "rule__Ordenacion__CorrectasAssignment_3_2");
					put(grammarAccess.getOrdenacionAccess().getCorrectasAssignment_3_3_1(), "rule__Ordenacion__CorrectasAssignment_3_3_1");
					put(grammarAccess.getOrdenacionAccess().getAlternativasAssignment_4_2(), "rule__Ordenacion__AlternativasAssignment_4_2");
					put(grammarAccess.getOrdenacionAccess().getAlternativasAssignment_4_3_1(), "rule__Ordenacion__AlternativasAssignment_4_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			autoevaluacion.ui.contentassist.antlr.internal.InternalAutoevaluacionParser typedParser = (autoevaluacion.ui.contentassist.antlr.internal.InternalAutoevaluacionParser) parser;
			typedParser.entryRuleHoja();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public AutoevaluacionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AutoevaluacionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
