/**
 * generated by Xtext
 */
package autoevaluacion.serializer;

import autoevaluacion.serializer.AbstractAutoevaluacionSyntacticSequencer;

@SuppressWarnings("all")
public class AutoevaluacionSyntacticSequencer extends AbstractAutoevaluacionSyntacticSequencer {
}
