/**
 * generated by Xtext
 */
package autoevaluacion.serializer;

import autoevaluacion.serializer.AbstractAutoevaluacionSemanticSequencer;

@SuppressWarnings("all")
public class AutoevaluacionSemanticSequencer extends AbstractAutoevaluacionSemanticSequencer {
}
