/*
* generated by Xtext
*/
package autoevaluacion.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import autoevaluacion.services.AutoevaluacionGrammarAccess;

public class AutoevaluacionParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AutoevaluacionGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected autoevaluacion.parser.antlr.internal.InternalAutoevaluacionParser createParser(XtextTokenStream stream) {
		return new autoevaluacion.parser.antlr.internal.InternalAutoevaluacionParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Hoja";
	}
	
	public AutoevaluacionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AutoevaluacionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
