/*
 * generated by Xtext
 */
package autoevaluacion.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AutoevaluacionUiModule extends autoevaluacion.ui.AbstractAutoevaluacionUiModule {
	public AutoevaluacionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
