/**
 * generated by Xtext
 */
package autoevaluacion.validation;

import autoevaluacion.validation.AbstractAutoevaluacionValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class AutoevaluacionValidator extends AbstractAutoevaluacionValidator {
}
