/*
* generated by Xtext
*/
package autoevaluacion.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class AutoevaluacionGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class HojaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Hoja");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cClasicoParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cWizardParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cWizardAdaptativoParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Hoja:
		//	Clasico | Wizard | WizardAdaptativo;
		public ParserRule getRule() { return rule; }

		//Clasico | Wizard | WizardAdaptativo
		public Alternatives getAlternatives() { return cAlternatives; }

		//Clasico
		public RuleCall getClasicoParserRuleCall_0() { return cClasicoParserRuleCall_0; }

		//Wizard
		public RuleCall getWizardParserRuleCall_1() { return cWizardParserRuleCall_1; }

		//WizardAdaptativo
		public RuleCall getWizardAdaptativoParserRuleCall_2() { return cWizardAdaptativoParserRuleCall_2; }
	}

	public class RespuestaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Respuesta");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRespuestaUnicaParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRespuestaMultipleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTextoLibreParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cOrdenacionParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Respuesta:
		//	RespuestaUnica | RespuestaMultiple | TextoLibre | Ordenacion;
		public ParserRule getRule() { return rule; }

		//RespuestaUnica | RespuestaMultiple | TextoLibre | Ordenacion
		public Alternatives getAlternatives() { return cAlternatives; }

		//RespuestaUnica
		public RuleCall getRespuestaUnicaParserRuleCall_0() { return cRespuestaUnicaParserRuleCall_0; }

		//RespuestaMultiple
		public RuleCall getRespuestaMultipleParserRuleCall_1() { return cRespuestaMultipleParserRuleCall_1; }

		//TextoLibre
		public RuleCall getTextoLibreParserRuleCall_2() { return cTextoLibreParserRuleCall_2; }

		//Ordenacion
		public RuleCall getOrdenacionParserRuleCall_3() { return cOrdenacionParserRuleCall_3; }
	}

	public class EjercicioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Ejercicio");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEjercicioKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEnunciadoKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cEnunciadoAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEnunciadoEStringParserRuleCall_4_0 = (RuleCall)cEnunciadoAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPuntuacionEjKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPuntuacionEjAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPuntuacionEjEDoubleParserRuleCall_5_1_0 = (RuleCall)cPuntuacionEjAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCategoriaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cCategoriaAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cCategoriaEStringParserRuleCall_6_1_0 = (RuleCall)cCategoriaAssignment_6_1.eContents().get(0);
		private final Keyword cOrderKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cOrderAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cOrderEIntParserRuleCall_8_0 = (RuleCall)cOrderAssignment_8.eContents().get(0);
		private final Keyword cRespuestaKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cRespuestaAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cRespuestaRespuestaParserRuleCall_10_0 = (RuleCall)cRespuestaAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Ejercicio:
		//	"Ejercicio" name=EString "{" "enunciado" enunciado=EString ("puntuacionEj" puntuacionEj=EDouble)? ("categoria"
		//	categoria=EString)? "order" order=EInt "respuesta" respuesta=Respuesta "}";
		public ParserRule getRule() { return rule; }

		//"Ejercicio" name=EString "{" "enunciado" enunciado=EString ("puntuacionEj" puntuacionEj=EDouble)? ("categoria"
		//categoria=EString)? "order" order=EInt "respuesta" respuesta=Respuesta "}"
		public Group getGroup() { return cGroup; }

		//"Ejercicio"
		public Keyword getEjercicioKeyword_0() { return cEjercicioKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"enunciado"
		public Keyword getEnunciadoKeyword_3() { return cEnunciadoKeyword_3; }

		//enunciado=EString
		public Assignment getEnunciadoAssignment_4() { return cEnunciadoAssignment_4; }

		//EString
		public RuleCall getEnunciadoEStringParserRuleCall_4_0() { return cEnunciadoEStringParserRuleCall_4_0; }

		//("puntuacionEj" puntuacionEj=EDouble)?
		public Group getGroup_5() { return cGroup_5; }

		//"puntuacionEj"
		public Keyword getPuntuacionEjKeyword_5_0() { return cPuntuacionEjKeyword_5_0; }

		//puntuacionEj=EDouble
		public Assignment getPuntuacionEjAssignment_5_1() { return cPuntuacionEjAssignment_5_1; }

		//EDouble
		public RuleCall getPuntuacionEjEDoubleParserRuleCall_5_1_0() { return cPuntuacionEjEDoubleParserRuleCall_5_1_0; }

		//("categoria" categoria=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"categoria"
		public Keyword getCategoriaKeyword_6_0() { return cCategoriaKeyword_6_0; }

		//categoria=EString
		public Assignment getCategoriaAssignment_6_1() { return cCategoriaAssignment_6_1; }

		//EString
		public RuleCall getCategoriaEStringParserRuleCall_6_1_0() { return cCategoriaEStringParserRuleCall_6_1_0; }

		//"order"
		public Keyword getOrderKeyword_7() { return cOrderKeyword_7; }

		//order=EInt
		public Assignment getOrderAssignment_8() { return cOrderAssignment_8; }

		//EInt
		public RuleCall getOrderEIntParserRuleCall_8_0() { return cOrderEIntParserRuleCall_8_0; }

		//"respuesta"
		public Keyword getRespuestaKeyword_9() { return cRespuestaKeyword_9; }

		//respuesta=Respuesta
		public Assignment getRespuestaAssignment_10() { return cRespuestaAssignment_10; }

		//Respuesta
		public RuleCall getRespuestaRespuestaParserRuleCall_10_0() { return cRespuestaRespuestaParserRuleCall_10_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble returns ecore::EDouble:
		//	"-"? INT? "." INT (("E" | "e") "-"? INT)?;
		public ParserRule getRule() { return rule; }

		//"-"? INT? "." INT (("E" | "e") "-"? INT)?
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }

		//"."
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }

		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }

		//(("E" | "e") "-"? INT)?
		public Group getGroup_4() { return cGroup_4; }

		//"E" | "e"
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }

		//"E"
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }

		//"e"
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }

		//"-"?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }

		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}

	public class ClasicoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Clasico");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClasicoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPuntuacionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPuntuacionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPuntuacionEDoubleParserRuleCall_3_0 = (RuleCall)cPuntuacionAssignment_3.eContents().get(0);
		private final Keyword cPenalizacionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPenalizacionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPenalizacionEDoubleParserRuleCall_5_0 = (RuleCall)cPenalizacionAssignment_5.eContents().get(0);
		private final Keyword cEjerciciosKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cEjerciciosAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cEjerciciosEjercicioParserRuleCall_8_0 = (RuleCall)cEjerciciosAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCommaKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cEjerciciosAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cEjerciciosEjercicioParserRuleCall_9_1_0 = (RuleCall)cEjerciciosAssignment_9_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Clasico:
		//	"Clasico" "{" "puntuacion" puntuacion=EDouble "penalizacion" penalizacion=EDouble "ejercicios" "{"
		//	ejercicios+=Ejercicio ("," ejercicios+=Ejercicio)* "}" "}";
		public ParserRule getRule() { return rule; }

		//"Clasico" "{" "puntuacion" puntuacion=EDouble "penalizacion" penalizacion=EDouble "ejercicios" "{" ejercicios+=Ejercicio
		//("," ejercicios+=Ejercicio)* "}" "}"
		public Group getGroup() { return cGroup; }

		//"Clasico"
		public Keyword getClasicoKeyword_0() { return cClasicoKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"puntuacion"
		public Keyword getPuntuacionKeyword_2() { return cPuntuacionKeyword_2; }

		//puntuacion=EDouble
		public Assignment getPuntuacionAssignment_3() { return cPuntuacionAssignment_3; }

		//EDouble
		public RuleCall getPuntuacionEDoubleParserRuleCall_3_0() { return cPuntuacionEDoubleParserRuleCall_3_0; }

		//"penalizacion"
		public Keyword getPenalizacionKeyword_4() { return cPenalizacionKeyword_4; }

		//penalizacion=EDouble
		public Assignment getPenalizacionAssignment_5() { return cPenalizacionAssignment_5; }

		//EDouble
		public RuleCall getPenalizacionEDoubleParserRuleCall_5_0() { return cPenalizacionEDoubleParserRuleCall_5_0; }

		//"ejercicios"
		public Keyword getEjerciciosKeyword_6() { return cEjerciciosKeyword_6; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }

		//ejercicios+=Ejercicio
		public Assignment getEjerciciosAssignment_8() { return cEjerciciosAssignment_8; }

		//Ejercicio
		public RuleCall getEjerciciosEjercicioParserRuleCall_8_0() { return cEjerciciosEjercicioParserRuleCall_8_0; }

		//("," ejercicios+=Ejercicio)*
		public Group getGroup_9() { return cGroup_9; }

		//","
		public Keyword getCommaKeyword_9_0() { return cCommaKeyword_9_0; }

		//ejercicios+=Ejercicio
		public Assignment getEjerciciosAssignment_9_1() { return cEjerciciosAssignment_9_1; }

		//Ejercicio
		public RuleCall getEjerciciosEjercicioParserRuleCall_9_1_0() { return cEjerciciosEjercicioParserRuleCall_9_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class WizardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Wizard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWizardKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPuntuacionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPuntuacionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPuntuacionEDoubleParserRuleCall_3_0 = (RuleCall)cPuntuacionAssignment_3.eContents().get(0);
		private final Keyword cPenalizacionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPenalizacionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPenalizacionEDoubleParserRuleCall_5_0 = (RuleCall)cPenalizacionAssignment_5.eContents().get(0);
		private final Keyword cEjerciciosKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cEjerciciosAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cEjerciciosEjercicioParserRuleCall_8_0 = (RuleCall)cEjerciciosAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCommaKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cEjerciciosAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cEjerciciosEjercicioParserRuleCall_9_1_0 = (RuleCall)cEjerciciosAssignment_9_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Wizard:
		//	"Wizard" "{" "puntuacion" puntuacion=EDouble "penalizacion" penalizacion=EDouble "ejercicios" "{"
		//	ejercicios+=Ejercicio ("," ejercicios+=Ejercicio)* "}" "}";
		public ParserRule getRule() { return rule; }

		//"Wizard" "{" "puntuacion" puntuacion=EDouble "penalizacion" penalizacion=EDouble "ejercicios" "{" ejercicios+=Ejercicio
		//("," ejercicios+=Ejercicio)* "}" "}"
		public Group getGroup() { return cGroup; }

		//"Wizard"
		public Keyword getWizardKeyword_0() { return cWizardKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"puntuacion"
		public Keyword getPuntuacionKeyword_2() { return cPuntuacionKeyword_2; }

		//puntuacion=EDouble
		public Assignment getPuntuacionAssignment_3() { return cPuntuacionAssignment_3; }

		//EDouble
		public RuleCall getPuntuacionEDoubleParserRuleCall_3_0() { return cPuntuacionEDoubleParserRuleCall_3_0; }

		//"penalizacion"
		public Keyword getPenalizacionKeyword_4() { return cPenalizacionKeyword_4; }

		//penalizacion=EDouble
		public Assignment getPenalizacionAssignment_5() { return cPenalizacionAssignment_5; }

		//EDouble
		public RuleCall getPenalizacionEDoubleParserRuleCall_5_0() { return cPenalizacionEDoubleParserRuleCall_5_0; }

		//"ejercicios"
		public Keyword getEjerciciosKeyword_6() { return cEjerciciosKeyword_6; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }

		//ejercicios+=Ejercicio
		public Assignment getEjerciciosAssignment_8() { return cEjerciciosAssignment_8; }

		//Ejercicio
		public RuleCall getEjerciciosEjercicioParserRuleCall_8_0() { return cEjerciciosEjercicioParserRuleCall_8_0; }

		//("," ejercicios+=Ejercicio)*
		public Group getGroup_9() { return cGroup_9; }

		//","
		public Keyword getCommaKeyword_9_0() { return cCommaKeyword_9_0; }

		//ejercicios+=Ejercicio
		public Assignment getEjerciciosAssignment_9_1() { return cEjerciciosAssignment_9_1; }

		//Ejercicio
		public RuleCall getEjerciciosEjercicioParserRuleCall_9_1_0() { return cEjerciciosEjercicioParserRuleCall_9_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class WizardAdaptativoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "WizardAdaptativo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWizardAdaptativoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPuntuacionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPuntuacionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPuntuacionEDoubleParserRuleCall_3_0 = (RuleCall)cPuntuacionAssignment_3.eContents().get(0);
		private final Keyword cPenalizacionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPenalizacionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPenalizacionEDoubleParserRuleCall_5_0 = (RuleCall)cPenalizacionAssignment_5.eContents().get(0);
		private final Keyword cEjerciciosKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cEjerciciosAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cEjerciciosEjercicioParserRuleCall_8_0 = (RuleCall)cEjerciciosAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCommaKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cEjerciciosAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cEjerciciosEjercicioParserRuleCall_9_1_0 = (RuleCall)cEjerciciosAssignment_9_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//WizardAdaptativo:
		//	"WizardAdaptativo" "{" "puntuacion" puntuacion=EDouble "penalizacion" penalizacion=EDouble "ejercicios" "{"
		//	ejercicios+=Ejercicio ("," ejercicios+=Ejercicio)* "}" "}";
		public ParserRule getRule() { return rule; }

		//"WizardAdaptativo" "{" "puntuacion" puntuacion=EDouble "penalizacion" penalizacion=EDouble "ejercicios" "{"
		//ejercicios+=Ejercicio ("," ejercicios+=Ejercicio)* "}" "}"
		public Group getGroup() { return cGroup; }

		//"WizardAdaptativo"
		public Keyword getWizardAdaptativoKeyword_0() { return cWizardAdaptativoKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"puntuacion"
		public Keyword getPuntuacionKeyword_2() { return cPuntuacionKeyword_2; }

		//puntuacion=EDouble
		public Assignment getPuntuacionAssignment_3() { return cPuntuacionAssignment_3; }

		//EDouble
		public RuleCall getPuntuacionEDoubleParserRuleCall_3_0() { return cPuntuacionEDoubleParserRuleCall_3_0; }

		//"penalizacion"
		public Keyword getPenalizacionKeyword_4() { return cPenalizacionKeyword_4; }

		//penalizacion=EDouble
		public Assignment getPenalizacionAssignment_5() { return cPenalizacionAssignment_5; }

		//EDouble
		public RuleCall getPenalizacionEDoubleParserRuleCall_5_0() { return cPenalizacionEDoubleParserRuleCall_5_0; }

		//"ejercicios"
		public Keyword getEjerciciosKeyword_6() { return cEjerciciosKeyword_6; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }

		//ejercicios+=Ejercicio
		public Assignment getEjerciciosAssignment_8() { return cEjerciciosAssignment_8; }

		//Ejercicio
		public RuleCall getEjerciciosEjercicioParserRuleCall_8_0() { return cEjerciciosEjercicioParserRuleCall_8_0; }

		//("," ejercicios+=Ejercicio)*
		public Group getGroup_9() { return cGroup_9; }

		//","
		public Keyword getCommaKeyword_9_0() { return cCommaKeyword_9_0; }

		//ejercicios+=Ejercicio
		public Assignment getEjerciciosAssignment_9_1() { return cEjerciciosAssignment_9_1; }

		//Ejercicio
		public RuleCall getEjerciciosEjercicioParserRuleCall_9_1_0() { return cEjerciciosEjercicioParserRuleCall_9_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class RespuestaUnicaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RespuestaUnica");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRespuestaUnicaAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRespuestaUnicaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCorrectasKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cCorrectasAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cCorrectasEStringParserRuleCall_3_2_0 = (RuleCall)cCorrectasAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cCorrectasAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cCorrectasEStringParserRuleCall_3_3_1_0 = (RuleCall)cCorrectasAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAlternativasKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cAlternativasAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cAlternativasEStringParserRuleCall_4_2_0 = (RuleCall)cAlternativasAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cAlternativasAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cAlternativasEStringParserRuleCall_4_3_1_0 = (RuleCall)cAlternativasAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//RespuestaUnica:
		//	{RespuestaUnica} "RespuestaUnica" "{" ("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")?
		//	("alternativas" "{" alternativas+=EString ("," alternativas+=EString)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{RespuestaUnica} "RespuestaUnica" "{" ("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")?
		//("alternativas" "{" alternativas+=EString ("," alternativas+=EString)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{RespuestaUnica}
		public Action getRespuestaUnicaAction_0() { return cRespuestaUnicaAction_0; }

		//"RespuestaUnica"
		public Keyword getRespuestaUnicaKeyword_1() { return cRespuestaUnicaKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"correctas"
		public Keyword getCorrectasKeyword_3_0() { return cCorrectasKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//correctas+=EString
		public Assignment getCorrectasAssignment_3_2() { return cCorrectasAssignment_3_2; }

		//EString
		public RuleCall getCorrectasEStringParserRuleCall_3_2_0() { return cCorrectasEStringParserRuleCall_3_2_0; }

		//("," correctas+=EString)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//correctas+=EString
		public Assignment getCorrectasAssignment_3_3_1() { return cCorrectasAssignment_3_3_1; }

		//EString
		public RuleCall getCorrectasEStringParserRuleCall_3_3_1_0() { return cCorrectasEStringParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//("alternativas" "{" alternativas+=EString ("," alternativas+=EString)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"alternativas"
		public Keyword getAlternativasKeyword_4_0() { return cAlternativasKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//alternativas+=EString
		public Assignment getAlternativasAssignment_4_2() { return cAlternativasAssignment_4_2; }

		//EString
		public RuleCall getAlternativasEStringParserRuleCall_4_2_0() { return cAlternativasEStringParserRuleCall_4_2_0; }

		//("," alternativas+=EString)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//alternativas+=EString
		public Assignment getAlternativasAssignment_4_3_1() { return cAlternativasAssignment_4_3_1; }

		//EString
		public RuleCall getAlternativasEStringParserRuleCall_4_3_1_0() { return cAlternativasEStringParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class RespuestaMultipleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RespuestaMultiple");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRespuestaMultipleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRespuestaMultipleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCorrectasKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cCorrectasAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cCorrectasEStringParserRuleCall_3_2_0 = (RuleCall)cCorrectasAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cCorrectasAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cCorrectasEStringParserRuleCall_3_3_1_0 = (RuleCall)cCorrectasAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAlternativasKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cAlternativasAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cAlternativasEStringParserRuleCall_4_2_0 = (RuleCall)cAlternativasAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cAlternativasAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cAlternativasEStringParserRuleCall_4_3_1_0 = (RuleCall)cAlternativasAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//RespuestaMultiple:
		//	{RespuestaMultiple} "RespuestaMultiple" "{" ("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")?
		//	("alternativas" "{" alternativas+=EString ("," alternativas+=EString)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{RespuestaMultiple} "RespuestaMultiple" "{" ("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")?
		//("alternativas" "{" alternativas+=EString ("," alternativas+=EString)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{RespuestaMultiple}
		public Action getRespuestaMultipleAction_0() { return cRespuestaMultipleAction_0; }

		//"RespuestaMultiple"
		public Keyword getRespuestaMultipleKeyword_1() { return cRespuestaMultipleKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"correctas"
		public Keyword getCorrectasKeyword_3_0() { return cCorrectasKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//correctas+=EString
		public Assignment getCorrectasAssignment_3_2() { return cCorrectasAssignment_3_2; }

		//EString
		public RuleCall getCorrectasEStringParserRuleCall_3_2_0() { return cCorrectasEStringParserRuleCall_3_2_0; }

		//("," correctas+=EString)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//correctas+=EString
		public Assignment getCorrectasAssignment_3_3_1() { return cCorrectasAssignment_3_3_1; }

		//EString
		public RuleCall getCorrectasEStringParserRuleCall_3_3_1_0() { return cCorrectasEStringParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//("alternativas" "{" alternativas+=EString ("," alternativas+=EString)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"alternativas"
		public Keyword getAlternativasKeyword_4_0() { return cAlternativasKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//alternativas+=EString
		public Assignment getAlternativasAssignment_4_2() { return cAlternativasAssignment_4_2; }

		//EString
		public RuleCall getAlternativasEStringParserRuleCall_4_2_0() { return cAlternativasEStringParserRuleCall_4_2_0; }

		//("," alternativas+=EString)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//alternativas+=EString
		public Assignment getAlternativasAssignment_4_3_1() { return cAlternativasAssignment_4_3_1; }

		//EString
		public RuleCall getAlternativasEStringParserRuleCall_4_3_1_0() { return cAlternativasEStringParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class TextoLibreElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TextoLibre");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTextoLibreAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTextoLibreKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCorrectasKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cCorrectasAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cCorrectasEStringParserRuleCall_3_2_0 = (RuleCall)cCorrectasAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cCorrectasAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cCorrectasEStringParserRuleCall_3_3_1_0 = (RuleCall)cCorrectasAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAlternativasKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cAlternativasAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cAlternativasEStringParserRuleCall_4_2_0 = (RuleCall)cAlternativasAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cAlternativasAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cAlternativasEStringParserRuleCall_4_3_1_0 = (RuleCall)cAlternativasAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//TextoLibre:
		//	{TextoLibre} "TextoLibre" "{" ("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")? ("alternativas" "{"
		//	alternativas+=EString ("," alternativas+=EString)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{TextoLibre} "TextoLibre" "{" ("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")? ("alternativas" "{"
		//alternativas+=EString ("," alternativas+=EString)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{TextoLibre}
		public Action getTextoLibreAction_0() { return cTextoLibreAction_0; }

		//"TextoLibre"
		public Keyword getTextoLibreKeyword_1() { return cTextoLibreKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"correctas"
		public Keyword getCorrectasKeyword_3_0() { return cCorrectasKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//correctas+=EString
		public Assignment getCorrectasAssignment_3_2() { return cCorrectasAssignment_3_2; }

		//EString
		public RuleCall getCorrectasEStringParserRuleCall_3_2_0() { return cCorrectasEStringParserRuleCall_3_2_0; }

		//("," correctas+=EString)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//correctas+=EString
		public Assignment getCorrectasAssignment_3_3_1() { return cCorrectasAssignment_3_3_1; }

		//EString
		public RuleCall getCorrectasEStringParserRuleCall_3_3_1_0() { return cCorrectasEStringParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//("alternativas" "{" alternativas+=EString ("," alternativas+=EString)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"alternativas"
		public Keyword getAlternativasKeyword_4_0() { return cAlternativasKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//alternativas+=EString
		public Assignment getAlternativasAssignment_4_2() { return cAlternativasAssignment_4_2; }

		//EString
		public RuleCall getAlternativasEStringParserRuleCall_4_2_0() { return cAlternativasEStringParserRuleCall_4_2_0; }

		//("," alternativas+=EString)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//alternativas+=EString
		public Assignment getAlternativasAssignment_4_3_1() { return cAlternativasAssignment_4_3_1; }

		//EString
		public RuleCall getAlternativasEStringParserRuleCall_4_3_1_0() { return cAlternativasEStringParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class OrdenacionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Ordenacion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOrdenacionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOrdenacionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCorrectasKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cCorrectasAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cCorrectasEStringParserRuleCall_3_2_0 = (RuleCall)cCorrectasAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cCorrectasAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cCorrectasEStringParserRuleCall_3_3_1_0 = (RuleCall)cCorrectasAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAlternativasKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cAlternativasAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cAlternativasEStringParserRuleCall_4_2_0 = (RuleCall)cAlternativasAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cAlternativasAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cAlternativasEStringParserRuleCall_4_3_1_0 = (RuleCall)cAlternativasAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Ordenacion:
		//	{Ordenacion} "Ordenacion" "{" ("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")? ("alternativas" "{"
		//	alternativas+=EString ("," alternativas+=EString)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{Ordenacion} "Ordenacion" "{" ("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")? ("alternativas" "{"
		//alternativas+=EString ("," alternativas+=EString)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{Ordenacion}
		public Action getOrdenacionAction_0() { return cOrdenacionAction_0; }

		//"Ordenacion"
		public Keyword getOrdenacionKeyword_1() { return cOrdenacionKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"correctas"
		public Keyword getCorrectasKeyword_3_0() { return cCorrectasKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//correctas+=EString
		public Assignment getCorrectasAssignment_3_2() { return cCorrectasAssignment_3_2; }

		//EString
		public RuleCall getCorrectasEStringParserRuleCall_3_2_0() { return cCorrectasEStringParserRuleCall_3_2_0; }

		//("," correctas+=EString)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//correctas+=EString
		public Assignment getCorrectasAssignment_3_3_1() { return cCorrectasAssignment_3_3_1; }

		//EString
		public RuleCall getCorrectasEStringParserRuleCall_3_3_1_0() { return cCorrectasEStringParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//("alternativas" "{" alternativas+=EString ("," alternativas+=EString)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"alternativas"
		public Keyword getAlternativasKeyword_4_0() { return cAlternativasKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//alternativas+=EString
		public Assignment getAlternativasAssignment_4_2() { return cAlternativasAssignment_4_2; }

		//EString
		public RuleCall getAlternativasEStringParserRuleCall_4_2_0() { return cAlternativasEStringParserRuleCall_4_2_0; }

		//("," alternativas+=EString)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//alternativas+=EString
		public Assignment getAlternativasAssignment_4_3_1() { return cAlternativasAssignment_4_3_1; }

		//EString
		public RuleCall getAlternativasEStringParserRuleCall_4_3_1_0() { return cAlternativasEStringParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	
	private HojaElements pHoja;
	private RespuestaElements pRespuesta;
	private EjercicioElements pEjercicio;
	private EDoubleElements pEDouble;
	private ClasicoElements pClasico;
	private WizardElements pWizard;
	private WizardAdaptativoElements pWizardAdaptativo;
	private EStringElements pEString;
	private EIntElements pEInt;
	private RespuestaUnicaElements pRespuestaUnica;
	private RespuestaMultipleElements pRespuestaMultiple;
	private TextoLibreElements pTextoLibre;
	private OrdenacionElements pOrdenacion;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public AutoevaluacionGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("autoevaluacion.Autoevaluacion".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Hoja:
	//	Clasico | Wizard | WizardAdaptativo;
	public HojaElements getHojaAccess() {
		return (pHoja != null) ? pHoja : (pHoja = new HojaElements());
	}
	
	public ParserRule getHojaRule() {
		return getHojaAccess().getRule();
	}

	//Respuesta:
	//	RespuestaUnica | RespuestaMultiple | TextoLibre | Ordenacion;
	public RespuestaElements getRespuestaAccess() {
		return (pRespuesta != null) ? pRespuesta : (pRespuesta = new RespuestaElements());
	}
	
	public ParserRule getRespuestaRule() {
		return getRespuestaAccess().getRule();
	}

	//Ejercicio:
	//	"Ejercicio" name=EString "{" "enunciado" enunciado=EString ("puntuacionEj" puntuacionEj=EDouble)? ("categoria"
	//	categoria=EString)? "order" order=EInt "respuesta" respuesta=Respuesta "}";
	public EjercicioElements getEjercicioAccess() {
		return (pEjercicio != null) ? pEjercicio : (pEjercicio = new EjercicioElements());
	}
	
	public ParserRule getEjercicioRule() {
		return getEjercicioAccess().getRule();
	}

	//EDouble returns ecore::EDouble:
	//	"-"? INT? "." INT (("E" | "e") "-"? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return (pEDouble != null) ? pEDouble : (pEDouble = new EDoubleElements());
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}

	//Clasico:
	//	"Clasico" "{" "puntuacion" puntuacion=EDouble "penalizacion" penalizacion=EDouble "ejercicios" "{"
	//	ejercicios+=Ejercicio ("," ejercicios+=Ejercicio)* "}" "}";
	public ClasicoElements getClasicoAccess() {
		return (pClasico != null) ? pClasico : (pClasico = new ClasicoElements());
	}
	
	public ParserRule getClasicoRule() {
		return getClasicoAccess().getRule();
	}

	//Wizard:
	//	"Wizard" "{" "puntuacion" puntuacion=EDouble "penalizacion" penalizacion=EDouble "ejercicios" "{"
	//	ejercicios+=Ejercicio ("," ejercicios+=Ejercicio)* "}" "}";
	public WizardElements getWizardAccess() {
		return (pWizard != null) ? pWizard : (pWizard = new WizardElements());
	}
	
	public ParserRule getWizardRule() {
		return getWizardAccess().getRule();
	}

	//WizardAdaptativo:
	//	"WizardAdaptativo" "{" "puntuacion" puntuacion=EDouble "penalizacion" penalizacion=EDouble "ejercicios" "{"
	//	ejercicios+=Ejercicio ("," ejercicios+=Ejercicio)* "}" "}";
	public WizardAdaptativoElements getWizardAdaptativoAccess() {
		return (pWizardAdaptativo != null) ? pWizardAdaptativo : (pWizardAdaptativo = new WizardAdaptativoElements());
	}
	
	public ParserRule getWizardAdaptativoRule() {
		return getWizardAdaptativoAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return (pEInt != null) ? pEInt : (pEInt = new EIntElements());
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//RespuestaUnica:
	//	{RespuestaUnica} "RespuestaUnica" "{" ("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")?
	//	("alternativas" "{" alternativas+=EString ("," alternativas+=EString)* "}")? "}";
	public RespuestaUnicaElements getRespuestaUnicaAccess() {
		return (pRespuestaUnica != null) ? pRespuestaUnica : (pRespuestaUnica = new RespuestaUnicaElements());
	}
	
	public ParserRule getRespuestaUnicaRule() {
		return getRespuestaUnicaAccess().getRule();
	}

	//RespuestaMultiple:
	//	{RespuestaMultiple} "RespuestaMultiple" "{" ("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")?
	//	("alternativas" "{" alternativas+=EString ("," alternativas+=EString)* "}")? "}";
	public RespuestaMultipleElements getRespuestaMultipleAccess() {
		return (pRespuestaMultiple != null) ? pRespuestaMultiple : (pRespuestaMultiple = new RespuestaMultipleElements());
	}
	
	public ParserRule getRespuestaMultipleRule() {
		return getRespuestaMultipleAccess().getRule();
	}

	//TextoLibre:
	//	{TextoLibre} "TextoLibre" "{" ("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")? ("alternativas" "{"
	//	alternativas+=EString ("," alternativas+=EString)* "}")? "}";
	public TextoLibreElements getTextoLibreAccess() {
		return (pTextoLibre != null) ? pTextoLibre : (pTextoLibre = new TextoLibreElements());
	}
	
	public ParserRule getTextoLibreRule() {
		return getTextoLibreAccess().getRule();
	}

	//Ordenacion:
	//	{Ordenacion} "Ordenacion" "{" ("correctas" "{" correctas+=EString ("," correctas+=EString)* "}")? ("alternativas" "{"
	//	alternativas+=EString ("," alternativas+=EString)* "}")? "}";
	public OrdenacionElements getOrdenacionAccess() {
		return (pOrdenacion != null) ? pOrdenacion : (pOrdenacion = new OrdenacionElements());
	}
	
	public ParserRule getOrdenacionRule() {
		return getOrdenacionAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
