/*
 * generated by Xtext
 */
package autoevaluacion;

import org.eclipse.emf.ecore.EOperation;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.emf.ecore.EValidator;
import org.eclipse.ocl.common.OCLConstants;
import org.eclipse.ocl.ecore.delegate.OCLInvocationDelegateFactory;
import org.eclipse.ocl.ecore.delegate.OCLSettingDelegateFactory;
import org.eclipse.ocl.ecore.delegate.OCLValidationDelegateFactory;

/**
 * Initialization support for running Xtext languages without equinox extension
 * registry
 */
public class AutoevaluacionStandaloneSetup extends
		AutoevaluacionStandaloneSetupGenerated {

	public static void doSetup() {
		new AutoevaluacionStandaloneSetup()
				.createInjectorAndDoEMFRegistration();
		String oclDelegateURI = OCLConstants.OCL_DELEGATE_URI;
		EOperation.Internal.InvocationDelegate.Factory.Registry.INSTANCE.put(
				oclDelegateURI, new OCLInvocationDelegateFactory.Global());
		EStructuralFeature.Internal.SettingDelegate.Factory.Registry.INSTANCE
				.put(oclDelegateURI, new OCLSettingDelegateFactory.Global());
		EValidator.ValidationDelegate.Registry.INSTANCE.put(oclDelegateURI,
				new OCLValidationDelegateFactory.Global());
	}

	/*
	 * public static void doSetup() { new
	 * AutoevaluacionStandaloneSetup().createInjectorAndDoEMFRegistration(); }
	 */
}
