/*
 * generated by Xtext
 */
package autoevaluacion;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AutoevaluacionRuntimeModule extends autoevaluacion.AbstractAutoevaluacionRuntimeModule {

}
